/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2020-02-25 02:01:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import java.util.ResourceBundle;
import org.wso2.carbon.identity.application.authentication.endpoint.util.AuthenticationEndpointUtil;
import org.wso2.carbon.identity.application.authentication.endpoint.util.EncodedControl;
import java.nio.charset.StandardCharsets;

public final class privacy_005fpolicy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/localize.jsp", Long.valueOf(1569960366000L));
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1571964730000L));
    _jspx_dependants.put("/includes/title.jsp", Long.valueOf(1571964730000L));
    _jspx_dependants.put("/includes/privacy-policy-content.jsp", Long.valueOf(1571964730000L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1571964730000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("org.wso2.carbon.identity.application.authentication.endpoint.util.EncodedControl");
    _jspx_imports_classes.add("org.wso2.carbon.identity.application.authentication.endpoint.util.AuthenticationEndpointUtil");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String BUNDLE = "org.wso2.carbon.identity.application.authentication.endpoint.i18n.Resources";
    ResourceBundle resourceBundle = ResourceBundle.getBundle(BUNDLE, request.getLocale(), new
            EncodedControl(StandardCharsets.UTF_8.toString()));

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <!-- title -->\n");
      out.write("    ");

        File titleFile = new File(getServletContext().getRealPath("extensions/title.jsp"));
        if (titleFile.exists()) {
    
      out.write("\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "extensions/title.jsp", out, false);
      out.write("\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- localize.jsp MUST already be included in the calling script -->\n");
      out.write("\n");
      out.write("<!-- title -->\n");
      out.write("<title>WSO2 API Manager</title>\n");
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"icon\" href=\"images/favicon.png\" type=\"image/x-icon\"/>\n");
      out.write("    <link href=\"libs/bootstrap_3.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/Roboto.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/custom-common.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"js/html5shiv.min.js\"></script>\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- header -->\n");

    File headerFile = new File(getServletContext().getRealPath("extensions/header.jsp"));
    if (headerFile.exists()) {

      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "extensions/header.jsp", out, false);
      out.write('\n');
 } else { 
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- localize.jsp MUST already be included in the calling script -->\n");
      out.write("\n");
      out.write("<!-- header -->\n");
      out.write("<header class=\"header header-default\">\n");
      out.write("    <div class=\"container-fluid\"><br></div>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"pull-left brand float-remove-xs text-center-xs\">\n");
      out.write("            <a href=\"#\">\n");
      out.write("                <img src=\"images/logo-inverse.svg\"\n");
      out.write("\t\t             alt=\"WSO2\"\n");
      out.write("                     title=\"WSO2\"\n");
      out.write("                     class=\"logo\">\n");
      out.write("                <h1><em>API Manager</em></h1>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write('\n');
 } 
      out.write("\n");
      out.write("\n");
      out.write("<!-- page content -->\n");

    File privacyPolicyFile = new File(getServletContext().getRealPath("extensions/privacy-policy-content.jsp"));
    if (privacyPolicyFile.exists()) {

      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "extensions/privacy-policy-content.jsp", out, false);
      out.write('\n');
 } else { 
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- page content -->\n");
      out.write("<div class=\"row\">\n");
      out.write("    <div class=\"col-xs-12 col-sm-3 col-md-3 col-lg-3 col-sm-offset-1 col-md-offset-1 col-lg-offset-1\">\n");
      out.write("        <div id=\"toc\"></div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"col-xs-12 col-sm-7 col-md-7 col-lg-7\">\n");
      out.write("        <!-- content -->\n");
      out.write("        <div class=\"container col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered wr-content wr-login col-centered padding-bottom-100\">\n");
      out.write("            <div>\n");
      out.write("                <h2 class=\"wr-title uppercase blue-bg padding-double white boarder-bottom-blue margin-none\">\n");
      out.write("                    WSO2 API Manager - Privacy Policy\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"boarder-all \">\n");
      out.write("                <div class=\"clearfix\"></div>\n");
      out.write("                ");
      out.write("\n");
      out.write("                <div id=\"privacyPolicy\" class=\"padding-double\">\n");
      out.write("                    <h4><a href=\"https://wso2.com/api-management/\"><strong>About WSO2 API Manager</strong></a></h4>\n");
      out.write("                    <p>WSO2 API Manager (referred hereafter as &ldquo;API-M &rdquo;) is an open source enterprise-class solution that supports API publishing, lifecycle management, application development, access control, rate limiting, and analytics in one cleanly integrated system.</p>\n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"privacy-policy\"><strong>Privacy Policy</strong></h2>\n");
      out.write("                    <p>This section explains how API-M captures your personal information, purpose of capturing, and the retention of your personal information.</p>\n");
      out.write("                    <p>Please note that this policy is for reference only, and is applicable for the software as a product. WSO2 Inc., or its developers have no access to the information held within API-M. Please refer &ldquo;Disclaimer&rdquo; for more information.</p>\n");
      out.write("                    <p>Entities, organisations or individuals controlling the use and administration of API-M should create their own privacy policies setting out the manner in which data is controlled or processed by the respective entity, organisation or individual.</p>                    \n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"what-are-the-personal-information\">What are the personal information &quest;</h2>\n");
      out.write("                    <p>API-M considers anything related to you as your personal information. This includes, but is not limited to,</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li>Your user name (except in the case where your user name is created by your employer under contract)</li>\n");
      out.write("                        <li>The IP address you use to login</li>\n");
      out.write("                        <li>Your device ID, if you choose to login with a device (Phone, Tablet)</li>\n");
      out.write("                    </ul>\n");
      out.write("                    <p>However API-M does not consider the following as your personal information, and  uses this only for <strong>analytical purposes</strong>, since this information cannot be used to track you.</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li>City/Country from which your TCP/IP connection originates</li>\n");
      out.write("                        <li>Time of the day you login.(Year, Month, Week, Hour or Minute)</li>\n");
      out.write("                        <li>Type of the device you use to login (Phone, Tablet, etc.)</li>\n");
      out.write("                        <li>Operating system and Generic browser information</li>\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"collection-of-your-information\">Collection of your information</h2>\n");
      out.write("                    <p>API-M collects your information to only serve your access requirements.</p>\n");
      out.write("                    <p>For example,</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li>API-M uses your IP address to detect any suspicious login attempt to your account. </li>\n");
      out.write("                        <li>API-M uses your First Name, Last Name, etc to provide rich and personalized information.</li>\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"tracking-technologies\">Tracking Technologies</h3>\n");
      out.write("                    <p>API-M collects your information through the following,</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li>The user sign up page where you enter your personal data</li>\n");
      out.write("                        <li>Tracking your IP address with HTTP request, HTTP headers, and TCP/IP</li>\n");
      out.write("                        <li>Tracking your geographic information with the IP address</li>\n");
      out.write("                        <li>Your login history with browser cookies. Please refer our <strong>cookie policy</strong> for more information</li>\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"user-of-your-personal-information\">Use of your personal information</h2>\n");
      out.write("                    <p>API-M will use your personal information only for the purposes for which it was collected (or for a use identified as consistent with that purpose).</p>\n");
      out.write("                    <p>API-M uses your personal information only for the following purposes.</p>\n");
      out.write("                    <ul>\n");
      out.write("                        <li>To provide you with a personalized user experience. API-M uses attributes such as your name for this purpose</li>\n");
      out.write("                        <li>To protect your account from unauthorized access or a potential hacking attempt. API-M use HTTP or TCP/IP Headers  for this purpose</li>\n");
      out.write("                        <ul>\n");
      out.write("                            <li>This includes,</li>\n");
      out.write("                            <ul>\n");
      out.write("                                <li>IP address,</li>\n");
      out.write("                                <li>Browser fingerprinting,</li>\n");
      out.write("                                <li>Cookies</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </ul>\n");
      out.write("                        <li>To derive statistical data for analytical purposes on system performance improvements. API-M will not keep any personal information after statistical calculations. Thus a statistical report has no means to identify an individual person</li>\n");
      out.write("                        <ul>\n");
      out.write("                            <li>API-M may use</li>\n");
      out.write("                            <ul>\n");
      out.write("                                <li>The IP Address to derive geographic information</li>\n");
      out.write("                                <li>Browser fingerprinting to determine the browser technology and version</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </ul>\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"disclosure-of-your-personal-information\">Disclosure of your personal information</h2>\n");
      out.write("                    <p>API-M will disclose personal information only for the purposes for which it was collected (or for a use identified as consistent with that purpose), unless you have consented otherwise or where it is required by law.</p>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"legal-process\">Legal process</h3>\n");
      out.write("                    <p>API-M  may disclose your personal information with or without your consent where it is required by law following the due and lawful process.</p>\n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"how-apim-store-or-keep-your-personal-information\">How API-M keeps your personal information</h2>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"where-your-personal-information-stored\">Where your personal information is stored</h3>\n");
      out.write("                    <p>API-M stores your personal information in secured databases. API-M exercises proper industry accepted security measures to protect the database where your personal information is held.</p>\n");
      out.write("                    <p>API-M may use encryption to keep your personal data with added level of security.</p>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"how-long-does-apim-keep-your-personal-information\">How long does API-M keep your personal information &quest;</h3>\n");
      out.write("                    <p>API-M keep your personal data as long as you are an active user of our system. You can update your personal data at any time with the given self-care user portals.</p>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"how-can-you-request-a-removal-of-your-personal-information\">How can you request a removal of your personal information &quest;</h3>\n");
      out.write("                    <p>You can request the administrator to delete your account The administrator will be the administrator of the tenant you are registered or the super-administrator if you do not use the tenant feature.</p>\n");
      out.write("                    <p>You can additionally request to anonymize all traces of your activities that may have been retained by API-M  in Logs, Databases or Analytical storage.</p>\n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"about\">About</h2>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"changes-to-this-policy\">Changes to this policy</h3>\n");
      out.write("                    <p>Upgraded versions of API-M may contain changes to this policy and revisions to this policy will be packaged within such upgrades. Such changes would only apply to users who choose to use upgraded versions.</p>\n");
      out.write("                    <p>The organization running API-M may revise the Privacy Policy from time to time. You can find the most recent governing policy with the respective link provided by the organization running API-M. The organization will notify any changes to the privacy policy over our official public channels.</p>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"your-choices\">Your choices</h3>\n");
      out.write("                    <p>If you already have an account with API Manager; you have the right to deactivate your account if you find that this privacy policy is unacceptable for you.</p>\n");
      out.write("                    <p>If you do not have an account, you can choose not to subscribe if you do not agree with our privacy policy.</p>\n");
      out.write("                    <div class=\"margin-bottom\"></div>\n");
      out.write("                    <h3 id=\"contact-us\">Contact us</h3>\n");
      out.write("                    <p>Please contact us if you have any question or concerns of this privacy policy.</p>\n");
      out.write("                    <p><a href=\"https://wso2.com/contact/\">https://wso2.com/contact/</a></p>\n");
      out.write("                    <div class=\"margin-bottom-double\"></div>\n");
      out.write("                    <h2 id=\"disclaimer\">Disclaimer</h2>\n");
      out.write("                    <ol>\n");
      out.write("                        <li>This privacy policy statement serves as a template for the organization running WSO2 API-M. The organizational policies will govern the real privacy policy applicable for its business purposes.</li>\n");
      out.write("                        <li>WSO2 or its employees, partners, affiliates do not have access to any data, including privacy-related data held at the organization running API-M.</li>\n");
      out.write("                        <li>This policy should be modified according to the organizational requirements.</li>\n");
      out.write("                    </ol>\n");
      out.write("                </div>\n");
      out.write("                ");
      out.write("\n");
      out.write("                <div class=\"clearfix\"></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- /content -->\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write('\n');
 } 
      out.write("\n");
      out.write("\n");
      out.write("<!-- footer -->\n");

    File footerFile = new File(getServletContext().getRealPath("extensions/footer.jsp"));
    if (footerFile.exists()) {

      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "extensions/footer.jsp", out, false);
      out.write('\n');
 } else { 
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- localize.jsp MUST already be included in the calling script -->\n");
      out.write("\n");
      out.write("<!-- footer -->\n");
      out.write("<footer class=\"footer\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <p>WSO2 API Manager | &copy;\n");
      out.write("            <script>document.write(new Date().getFullYear());</script>\n");
      out.write("            <a href=\"https://wso2.com/\"\n");
      out.write("               target=\"_blank\">\n");
      out.write("               <i class=\"icon fw fw-wso2\"></i>\n");
      out.write("               Inc\n");
      out.write("            </a>\n");
      out.write("            . All rights reserved\n");
      out.write("        </p>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write('\n');
 } 
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"libs/jquery_3.4.1/jquery-3.4.1.js\"></script>\n");
      out.write("<script src=\"libs/bootstrap_3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"js/u2f-api.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    var ToC = \"<nav role='navigation' class='table-of-contents'>\" + \"<h4>On this page:</h4>\" + \"<ul>\";\n");
      out.write("    var newLine, el, title, link;\n");
      out.write("\n");
      out.write("    $(\"#privacyPolicy h2,#privacyPolicy h3\").each(function() {\n");
      out.write("        el = $(this);\n");
      out.write("        title = el.text();\n");
      out.write("        link = \"#\" + el.attr(\"id\");\n");
      out.write("        if(el.is(\"h3\")){\n");
      out.write("            newLine = \"<li class='sub'>\" + \"<a href='\" + link + \"'>\" + title + \"</a>\" + \"</li>\";\n");
      out.write("        }else{\n");
      out.write("            newLine = \"<li >\" + \"<a href='\" + link + \"'>\" + title + \"</a>\" + \"</li>\";\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        ToC += newLine;\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    ToC += \"</ul>\" + \"</nav>\";\n");
      out.write("\n");
      out.write("    $(\"#toc\").append(ToC);\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
